import {Images} from "../constants/images";

export const servicesContent = [
    {
        id: "1",
        icon: Images.warehouseIcon,
        title: 'Warehouse',
        subTitle: 'Stocking facility at farm gate',
        desc: 'Scientifically managed warehouses at farmgate where farmers can store even a single bag of grains and convert them into digital assets',
        mainImg: Images.warehouse,
        subImg1: Images.warehouseDetails,
        subImg2: '',
    },
    {
        id: "2",
        icon: Images.creditIcon,
        title: 'Credit facility',
        subTitle: 'Capital for farmers',
        desc: 'Credit available from partner banks/NBFCs against grains stored within SFED accredited warehouses',
        mainImg: Images.credit,
        subImg1: Images.creditDetails,
        subImg2: '',
    },
    {
        id: "3",
        icon: Images.marketLinkageIcon,
        title: 'Market linkages',
        subTitle: 'Trading platform to sell commodities',
        desc: 'Farmers can now sell whenever they want through in class-Agri Trading Platform',
        mainImg: Images.marketLinkage,
        subImg1: Images.marketLinkageDetails,
        subImg2: '',
    },
    {
        id: "4",
        icon: Images.marketIntelligenceIcon,
        title: 'Market intelligence',
        subTitle: 'Realtime mandi rates',
        desc: 'Get access to Commodity Spot Rates and Market arrivals at your fingertips',
        mainImg: Images.marketIntelligence,
        subImg1: Images.marketIntelligenceDetails,
        subImg2: Images.marketIntelligenceDetails1,
    },
    {
        id: "5",
        icon: Images.paymentsIcon,
        title: 'payments',
        subTitle: 'Online payments facility',
        desc: 'Making quick, safe, and real-time payments to farmers  24*7',
        mainImg: Images.payments,
        subImg1: Images.paymentsDetails,
        subImg2: '',
    },
    {
        id: "6",
        icon: Images.agriInputIcon,
        title: 'agri-input',
        subTitle: 'All agri input available at one place',
        desc: 'Farmer can order the best quality input through SFED App at a very reasonable price.',
        mainImg: Images.agriInput,
        subImg1: '',
        subImg2: '',
    },

]